################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
autogen \
autogen/zap-generated \
autogen/zap-generated/app \
autogen/zap-generated/attributes \
matter_2.4.0/slc/component/sdk-content/simplicity-sdk/util/third_party/segger/systemview/SEGGER \
matter_2.4.0/third_party/QR-Code-generator/c \
matter_2.4.0/third_party/matter_sdk/examples/platform/silabs \
matter_2.4.0/third_party/matter_sdk/examples/platform/silabs/display \
matter_2.4.0/third_party/matter_sdk/examples/platform/silabs/provision \
matter_2.4.0/third_party/matter_sdk/examples/providers \
matter_2.4.0/third_party/matter_sdk/examples/shell/shell_common \
matter_2.4.0/third_party/matter_sdk/src/access \
matter_2.4.0/third_party/matter_sdk/src/access/examples \
matter_2.4.0/third_party/matter_sdk/src/app \
matter_2.4.0/third_party/matter_sdk/src/app/MessageDef \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/access-control-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/administrator-commissioning-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/basic-information \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/color-control-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/descriptor \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/diagnostic-logs-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/fixed-label-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/general-commissioning-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/general-diagnostics-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/group-key-mgmt-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/groups-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/identify-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/level-control \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/localization-configuration-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/network-commissioning \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/on-off-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/operational-credentials-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/ota-requestor \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/power-source-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/scenes-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/software-diagnostics-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/thread-network-diagnostics-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/time-format-localization-server \
matter_2.4.0/third_party/matter_sdk/src/app/clusters/user-label-server \
matter_2.4.0/third_party/matter_sdk/src/app/data-model \
matter_2.4.0/third_party/matter_sdk/src/app/data-model-provider \
matter_2.4.0/third_party/matter_sdk/src/app/reporting \
matter_2.4.0/third_party/matter_sdk/src/app/server \
matter_2.4.0/third_party/matter_sdk/src/app/util \
matter_2.4.0/third_party/matter_sdk/src/ble \
matter_2.4.0/third_party/matter_sdk/src/credentials \
matter_2.4.0/third_party/matter_sdk/src/credentials/attestation_verifier \
matter_2.4.0/third_party/matter_sdk/src/credentials/examples \
matter_2.4.0/third_party/matter_sdk/src/credentials/tests \
matter_2.4.0/third_party/matter_sdk/src/crypto \
matter_2.4.0/third_party/matter_sdk/src/inet \
matter_2.4.0/third_party/matter_sdk/src/lib/address_resolve \
matter_2.4.0/third_party/matter_sdk/src/lib/asn1 \
matter_2.4.0/third_party/matter_sdk/src/lib/core \
matter_2.4.0/third_party/matter_sdk/src/lib/dnssd \
matter_2.4.0/third_party/matter_sdk/src/lib/shell \
matter_2.4.0/third_party/matter_sdk/src/lib/shell/commands \
matter_2.4.0/third_party/matter_sdk/src/lib/support \
matter_2.4.0/third_party/matter_sdk/src/lib/support/logging \
matter_2.4.0/third_party/matter_sdk/src/lib/support/verhoeff \
matter_2.4.0/third_party/matter_sdk/src/messaging \
matter_2.4.0/third_party/matter_sdk/src/platform \
matter_2.4.0/third_party/matter_sdk/src/platform/FreeRTOS \
matter_2.4.0/third_party/matter_sdk/src/platform/OpenThread \
matter_2.4.0/third_party/matter_sdk/src/platform/silabs \
matter_2.4.0/third_party/matter_sdk/src/platform/silabs/efr32 \
matter_2.4.0/third_party/matter_sdk/src/platform/silabs/platformAbstraction \
matter_2.4.0/third_party/matter_sdk/src/protocols \
matter_2.4.0/third_party/matter_sdk/src/protocols/bdx \
matter_2.4.0/third_party/matter_sdk/src/protocols/echo \
matter_2.4.0/third_party/matter_sdk/src/protocols/interaction_model \
matter_2.4.0/third_party/matter_sdk/src/protocols/secure_channel \
matter_2.4.0/third_party/matter_sdk/src/protocols/user_directed_commissioning \
matter_2.4.0/third_party/matter_sdk/src/setup_payload \
matter_2.4.0/third_party/matter_sdk/src/system \
matter_2.4.0/third_party/matter_sdk/src/tracing \
matter_2.4.0/third_party/matter_sdk/src/transport \
matter_2.4.0/third_party/matter_sdk/src/transport/raw \
simplicity_sdk_2024.6.2/hardware/board/src \
simplicity_sdk_2024.6.2/hardware/driver/memlcd/src/memlcd_usart \
simplicity_sdk_2024.6.2/hardware/driver/memlcd/src \
simplicity_sdk_2024.6.2/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
simplicity_sdk_2024.6.2/platform/CMSIS/RTOS2/Source \
simplicity_sdk_2024.6.2/platform/Device/SiliconLabs/EFR32MG24/Source \
simplicity_sdk_2024.6.2/platform/bootloader/api \
simplicity_sdk_2024.6.2/platform/bootloader/app_properties \
simplicity_sdk_2024.6.2/platform/common/src \
simplicity_sdk_2024.6.2/platform/driver/button/src \
simplicity_sdk_2024.6.2/platform/driver/leddrv/src \
simplicity_sdk_2024.6.2/platform/emdrv/dmadrv/src \
simplicity_sdk_2024.6.2/platform/emdrv/gpiointerrupt/src \
simplicity_sdk_2024.6.2/platform/emdrv/nvm3/src \
simplicity_sdk_2024.6.2/platform/emdrv/uartdrv/src \
simplicity_sdk_2024.6.2/platform/emlib/src \
simplicity_sdk_2024.6.2/platform/middleware/glib/dmd/display \
simplicity_sdk_2024.6.2/platform/middleware/glib/fonts \
simplicity_sdk_2024.6.2/platform/middleware/glib/glib \
simplicity_sdk_2024.6.2/platform/peripheral/src \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/pa-conversions \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24 \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_built_in_phys \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_dma \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_pti \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_rssi \
simplicity_sdk_2024.6.2/platform/radio/rail_lib/plugin/rail_util_sequencer \
simplicity_sdk_2024.6.2/platform/security/sl_component/se_manager/src \
simplicity_sdk_2024.6.2/platform/security/sl_component/sl_mbedtls_support/src \
simplicity_sdk_2024.6.2/platform/security/sl_component/sl_protocol_crypto/src \
simplicity_sdk_2024.6.2/platform/security/sl_component/sl_psa_driver/src \
simplicity_sdk_2024.6.2/platform/service/clock_manager/src \
simplicity_sdk_2024.6.2/platform/service/device_init/src \
simplicity_sdk_2024.6.2/platform/service/device_manager/clocks \
simplicity_sdk_2024.6.2/platform/service/device_manager/devices \
simplicity_sdk_2024.6.2/platform/service/device_manager/src \
simplicity_sdk_2024.6.2/platform/service/hfxo_manager/src \
simplicity_sdk_2024.6.2/platform/service/interrupt_manager/src \
simplicity_sdk_2024.6.2/platform/service/iostream/src \
simplicity_sdk_2024.6.2/platform/service/memory_manager/profiler/src \
simplicity_sdk_2024.6.2/platform/service/memory_manager/src \
simplicity_sdk_2024.6.2/platform/service/mpu/src \
simplicity_sdk_2024.6.2/platform/service/power_manager/src \
simplicity_sdk_2024.6.2/platform/service/sleeptimer/src \
simplicity_sdk_2024.6.2/platform/service/system/src \
simplicity_sdk_2024.6.2/platform/service/udelay/src \
simplicity_sdk_2024.6.2/protocol/bluetooth/bgcommon/src \
simplicity_sdk_2024.6.2/protocol/bluetooth/src \
simplicity_sdk_2024.6.2/protocol/openthread/platform-abstraction/efr32 \
simplicity_sdk_2024.6.2/protocol/openthread/platform-abstraction/rtos/rtos-wrappers \
simplicity_sdk_2024.6.2/protocol/openthread/platform-abstraction/rtos \
simplicity_sdk_2024.6.2/protocol/openthread/src/cli \
simplicity_sdk_2024.6.2/util/plugin/security_manager \
simplicity_sdk_2024.6.2/util/silicon_labs/silabs_core/queue \
simplicity_sdk_2024.6.2/util/third_party/freertos/cmsis/Source \
simplicity_sdk_2024.6.2/util/third_party/freertos/kernel \
simplicity_sdk_2024.6.2/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure \
simplicity_sdk_2024.6.2/util/third_party/freertos/kernel/portable/MemMang \
simplicity_sdk_2024.6.2/util/third_party/freertos/kernel/portable/SiliconLabs \
simplicity_sdk_2024.6.2/util/third_party/mbedtls/library \
simplicity_sdk_2024.6.2/util/third_party/openthread/examples/apps/cli \
simplicity_sdk_2024.6.2/util/third_party/openthread/examples/platforms/utils \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/cli \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/api \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/backbone_router \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/border_router \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/coap \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/common \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/crypto \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/diags \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/instance \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/mac \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/meshcop \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/net \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/radio \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/thread \
simplicity_sdk_2024.6.2/util/third_party/openthread/src/core/utils \
simplicity_sdk_2024.6.2/util/third_party/openthread/third_party/tcplp/bsdtcp/cc \
simplicity_sdk_2024.6.2/util/third_party/openthread/third_party/tcplp/bsdtcp \
simplicity_sdk_2024.6.2/util/third_party/openthread/third_party/tcplp/lib \
src \

